





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;



namespace Books.Foundation.Orm.Models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        string Url { get; }
	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }
	}
}
namespace Books.Foundation.Orm.Models.sitecore.templates.Feature.Carousel.Carousel_Content
{


 	/// <summary>
	/// ICarouselItem Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Carousel/Carousel Content/CarouselItem</para>	
	/// <para>ID: 1ca6b74e-4583-4add-8544-ae0924fa932e</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarouselItemConstants.TemplateIdString, AutoMap = true )] //, Cachable = true
	public partial interface ICarouselItem : IGlassBase 
	{
								/// <summary>
					/// The Caption field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: c8490278-12b9-492d-8a68-af5e3caa5127</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICarouselItemConstants.CaptionFieldName)]
					string Caption  {get; set;}
			
								/// <summary>
					/// The Class field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 69a17318-c3b3-4968-b7d9-f78d91a1a89b</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICarouselItemConstants.ClassFieldName)]
					string Class  {get; set;}
			
								/// <summary>
					/// The Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: a22e7b0a-391e-4ad2-ae1e-9f4f4488022d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICarouselItemConstants.ImageFieldName)]
					Image Image  {get; set;}
			
								/// <summary>
					/// The ImageAlt field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 9d51e97b-7f5d-4a34-b390-b5afec192821</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICarouselItemConstants.ImageAltFieldName)]
					string ImageAlt  {get; set;}
			
								/// <summary>
					/// The ShowCaption field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 32ac5148-d40d-4dfa-866f-db5d77c7261b</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICarouselItemConstants.ShowCaptionFieldName)]
					bool ShowCaption  {get; set;}
			
				}


	public static partial class ICarouselItemConstants{

			public const string TemplateIdString = "1ca6b74e-4583-4add-8544-ae0924fa932e";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "CarouselItem";

					
			public static readonly ID CaptionFieldId = new ID("c8490278-12b9-492d-8a68-af5e3caa5127");
			public const string CaptionFieldName = "Caption";
			
					
			public static readonly ID ClassFieldId = new ID("69a17318-c3b3-4968-b7d9-f78d91a1a89b");
			public const string ClassFieldName = "Class";
			
					
			public static readonly ID ImageFieldId = new ID("a22e7b0a-391e-4ad2-ae1e-9f4f4488022d");
			public const string ImageFieldName = "Image";
			
					
			public static readonly ID ImageAltFieldId = new ID("9d51e97b-7f5d-4a34-b390-b5afec192821");
			public const string ImageAltFieldName = "ImageAlt";
			
					
			public static readonly ID ShowCaptionFieldId = new ID("32ac5148-d40d-4dfa-866f-db5d77c7261b");
			public const string ShowCaptionFieldName = "ShowCaption";
			
			

	}

	
	/// <summary>
	/// CarouselItem
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Carousel/Carousel Content/CarouselItem</para>	
	/// <para>ID: 1ca6b74e-4583-4add-8544-ae0924fa932e</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarouselItemConstants.TemplateIdString, AutoMap = true)] //, Cachable = true
	public partial class CarouselItem  : GlassBase, ICarouselItem 
	{
	   
						/// <summary>
				/// The Caption field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: c8490278-12b9-492d-8a68-af5e3caa5127</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarouselItemConstants.CaptionFieldName)]
				public virtual string Caption  {get; set;}
					
						/// <summary>
				/// The Class field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 69a17318-c3b3-4968-b7d9-f78d91a1a89b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarouselItemConstants.ClassFieldName)]
				public virtual string Class  {get; set;}
					
						/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: a22e7b0a-391e-4ad2-ae1e-9f4f4488022d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarouselItemConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
						/// <summary>
				/// The ImageAlt field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 9d51e97b-7f5d-4a34-b390-b5afec192821</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarouselItemConstants.ImageAltFieldName)]
				public virtual string ImageAlt  {get; set;}
					
						/// <summary>
				/// The ShowCaption field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 32ac5148-d40d-4dfa-866f-db5d77c7261b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarouselItemConstants.ShowCaptionFieldName)]
				public virtual bool ShowCaption  {get; set;}
					
			
	}
}
namespace Books.Foundation.Orm.Models.sitecore.templates.User_Defined.Base
{


 	/// <summary>
	/// I_Base_Content Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Base/_Base Content</para>	
	/// <para>ID: 2d0be1ce-5197-4110-a507-54fe2c4f753d</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_ContentConstants.TemplateIdString, AutoMap = true )] //, Cachable = true
	public partial interface I_Base_Content : IGlassBase 
	{
								/// <summary>
					/// The ContentBody field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: 8af829a4-3a05-4df4-8028-9505c7fd3d65</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Base_ContentConstants.ContentBodyFieldName)]
					string ContentBody  {get; set;}
			
				}


	public static partial class I_Base_ContentConstants{

			public const string TemplateIdString = "2d0be1ce-5197-4110-a507-54fe2c4f753d";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Base Content";

					
			public static readonly ID ContentBodyFieldId = new ID("8af829a4-3a05-4df4-8028-9505c7fd3d65");
			public const string ContentBodyFieldName = "ContentBody";
			
			

	}

	
	/// <summary>
	/// _Base_Content
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Base/_Base Content</para>	
	/// <para>ID: 2d0be1ce-5197-4110-a507-54fe2c4f753d</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_ContentConstants.TemplateIdString, AutoMap = true)] //, Cachable = true
	public partial class _Base_Content  : GlassBase, I_Base_Content 
	{
	   
						/// <summary>
				/// The ContentBody field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 8af829a4-3a05-4df4-8028-9505c7fd3d65</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Base_ContentConstants.ContentBodyFieldName)]
				public virtual string ContentBody  {get; set;}
					
			
	}
}
namespace Books.Foundation.Orm.Models.sitecore.templates.Feature.Footer
{


 	/// <summary>
	/// IFooter_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Footer/Footer Folder</para>	
	/// <para>ID: 30c11690-92f2-457e-846c-804368424e1a</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFooter_FolderConstants.TemplateIdString, AutoMap = true )] //, Cachable = true
	public partial interface IFooter_Folder : IGlassBase 
	{
				}


	public static partial class IFooter_FolderConstants{

			public const string TemplateIdString = "30c11690-92f2-457e-846c-804368424e1a";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Footer Folder";

			

	}

	
	/// <summary>
	/// Footer_Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Footer/Footer Folder</para>	
	/// <para>ID: 30c11690-92f2-457e-846c-804368424e1a</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFooter_FolderConstants.TemplateIdString, AutoMap = true)] //, Cachable = true
	public partial class Footer_Folder  : GlassBase, IFooter_Folder 
	{
	   
			
	}
}
namespace Books.Foundation.Orm.Models.sitecore.templates.User_Defined.Base
{


 	/// <summary>
	/// IBasePage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Base/BasePage</para>	
	/// <para>ID: 38c71966-b6ac-4280-a086-157cf33fa6ed</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBasePageConstants.TemplateIdString, AutoMap = true )] //, Cachable = true
	public partial interface IBasePage : IGlassBase 
	{
								/// <summary>
					/// The Sub Title field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 43260204-717e-421e-aeb0-5b8e572a4d26</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBasePageConstants.Sub_TitleFieldName)]
					string Sub_Title  {get; set;}
			
								/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: e8674014-f36c-407f-8217-9c16bd3d9adf</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBasePageConstants.TitleFieldName)]
					string Title  {get; set;}
			
								/// <summary>
					/// The MetaDescription field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: ed4089e1-c500-4c02-beaf-bd624ca82270</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBasePageConstants.MetaDescriptionFieldName)]
					string MetaDescription  {get; set;}
			
								/// <summary>
					/// The MetaTitle field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 0f80d938-d0aa-4191-9f44-7f1c32a39ce4</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBasePageConstants.MetaTitleFieldName)]
					string MetaTitle  {get; set;}
			
				}


	public static partial class IBasePageConstants{

			public const string TemplateIdString = "38c71966-b6ac-4280-a086-157cf33fa6ed";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "BasePage";

					
			public static readonly ID Sub_TitleFieldId = new ID("43260204-717e-421e-aeb0-5b8e572a4d26");
			public const string Sub_TitleFieldName = "Sub Title";
			
					
			public static readonly ID TitleFieldId = new ID("e8674014-f36c-407f-8217-9c16bd3d9adf");
			public const string TitleFieldName = "Title";
			
					
			public static readonly ID MetaDescriptionFieldId = new ID("ed4089e1-c500-4c02-beaf-bd624ca82270");
			public const string MetaDescriptionFieldName = "MetaDescription";
			
					
			public static readonly ID MetaTitleFieldId = new ID("0f80d938-d0aa-4191-9f44-7f1c32a39ce4");
			public const string MetaTitleFieldName = "MetaTitle";
			
			

	}

	
	/// <summary>
	/// BasePage
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Base/BasePage</para>	
	/// <para>ID: 38c71966-b6ac-4280-a086-157cf33fa6ed</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBasePageConstants.TemplateIdString, AutoMap = true)] //, Cachable = true
	public partial class BasePage  : GlassBase, IBasePage 
	{
	   
						/// <summary>
				/// The Sub Title field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 43260204-717e-421e-aeb0-5b8e572a4d26</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBasePageConstants.Sub_TitleFieldName)]
				public virtual string Sub_Title  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: e8674014-f36c-407f-8217-9c16bd3d9adf</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBasePageConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ed4089e1-c500-4c02-beaf-bd624ca82270</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBasePageConstants.MetaDescriptionFieldName)]
				public virtual string MetaDescription  {get; set;}
					
						/// <summary>
				/// The MetaTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 0f80d938-d0aa-4191-9f44-7f1c32a39ce4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBasePageConstants.MetaTitleFieldName)]
				public virtual string MetaTitle  {get; set;}
					
			
	}
}
namespace Books.Foundation.Orm.Models.sitecore.templates.Project.Page_Types
{


 	/// <summary>
	/// IGenres Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Page Types/Genres</para>	
	/// <para>ID: 3cc45f70-a4cd-47ce-b4a1-aa05aa67a19d</para>	
	/// </summary>
	[SitecoreType(TemplateId=IGenresConstants.TemplateIdString, AutoMap = true )] //, Cachable = true
	public partial interface IGenres : IGlassBase , global::Books.Foundation.Orm.Models.sitecore.templates.User_Defined.Base.IBase_Footer, global::Books.Foundation.Orm.Models.sitecore.templates.User_Defined.Base.IBasePage
	{
				}


	public static partial class IGenresConstants{

			public const string TemplateIdString = "3cc45f70-a4cd-47ce-b4a1-aa05aa67a19d";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Genres";

					
			public static readonly ID ContentFieldId = new ID("ff5ce688-42c6-47fe-97fc-ace47571a222");
			public const string ContentFieldName = "Content";
			
					
			public static readonly ID CopyrightFieldId = new ID("477c7db6-ceb4-4da4-84d4-c482d897ac2c");
			public const string CopyrightFieldName = "Copyright";
			
					
			public static readonly ID HeaderFieldId = new ID("672c7e6a-6e84-4936-a07e-0ff82aa2f957");
			public const string HeaderFieldName = "Header";
			
					
			public static readonly ID SubheadFieldId = new ID("cb8bd673-36f1-4793-8310-3f02fdca1a86");
			public const string SubheadFieldName = "Subhead";
			
					
			public static readonly ID Sub_TitleFieldId = new ID("43260204-717e-421e-aeb0-5b8e572a4d26");
			public const string Sub_TitleFieldName = "Sub Title";
			
					
			public static readonly ID TitleFieldId = new ID("e8674014-f36c-407f-8217-9c16bd3d9adf");
			public const string TitleFieldName = "Title";
			
					
			public static readonly ID MetaDescriptionFieldId = new ID("ed4089e1-c500-4c02-beaf-bd624ca82270");
			public const string MetaDescriptionFieldName = "MetaDescription";
			
					
			public static readonly ID MetaTitleFieldId = new ID("0f80d938-d0aa-4191-9f44-7f1c32a39ce4");
			public const string MetaTitleFieldName = "MetaTitle";
			
			

	}

	
	/// <summary>
	/// Genres
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Page Types/Genres</para>	
	/// <para>ID: 3cc45f70-a4cd-47ce-b4a1-aa05aa67a19d</para>	
	/// </summary>
	[SitecoreType(TemplateId=IGenresConstants.TemplateIdString, AutoMap = true)] //, Cachable = true
	public partial class Genres  : GlassBase, IGenres 
	{
	   
						/// <summary>
				/// The Content field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: ff5ce688-42c6-47fe-97fc-ace47571a222</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IGenresConstants.ContentFieldName)]
				public virtual string Content  {get; set;}
					
						/// <summary>
				/// The Copyright field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 477c7db6-ceb4-4da4-84d4-c482d897ac2c</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IGenresConstants.CopyrightFieldName)]
				public virtual string Copyright  {get; set;}
					
						/// <summary>
				/// The Header field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 672c7e6a-6e84-4936-a07e-0ff82aa2f957</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IGenresConstants.HeaderFieldName)]
				public virtual string Header  {get; set;}
					
						/// <summary>
				/// The Subhead field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: cb8bd673-36f1-4793-8310-3f02fdca1a86</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IGenresConstants.SubheadFieldName)]
				public virtual string Subhead  {get; set;}
					
						/// <summary>
				/// The Sub Title field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 43260204-717e-421e-aeb0-5b8e572a4d26</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IGenresConstants.Sub_TitleFieldName)]
				public virtual string Sub_Title  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: e8674014-f36c-407f-8217-9c16bd3d9adf</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IGenresConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ed4089e1-c500-4c02-beaf-bd624ca82270</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IGenresConstants.MetaDescriptionFieldName)]
				public virtual string MetaDescription  {get; set;}
					
						/// <summary>
				/// The MetaTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 0f80d938-d0aa-4191-9f44-7f1c32a39ce4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IGenresConstants.MetaTitleFieldName)]
				public virtual string MetaTitle  {get; set;}
					
			
	}
}
namespace Books.Foundation.Orm.Models.sitecore.templates.Feature.Carousel.Carousel_Content
{


 	/// <summary>
	/// ICarousel Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Carousel/Carousel Content/Carousel</para>	
	/// <para>ID: 49393afb-4a02-4f34-acf1-fec86916bb47</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarouselConstants.TemplateIdString, AutoMap = true )] //, Cachable = true
	public partial interface ICarousel : IGlassBase 
	{
								/// <summary>
					/// The Items field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 24071b88-2093-4f1e-9b6a-f3aa274a64ac</para>
					/// <para>Custom Data: generic=Books.Foundation.Orm.Models.sitecore.templates.Feature.Carousel.Carousel_Content.ICarouselItem</para>
					/// </summary>
					[SitecoreField(ICarouselConstants.ItemsFieldName)]
					IEnumerable<Books.Foundation.Orm.Models.sitecore.templates.Feature.Carousel.Carousel_Content.ICarouselItem> Items  {get; set;}
			
								/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: edaf25d3-c80a-45b2-8d90-7ca4db15080e</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICarouselConstants.TitleFieldName)]
					string Title  {get; set;}
			
				}


	public static partial class ICarouselConstants{

			public const string TemplateIdString = "49393afb-4a02-4f34-acf1-fec86916bb47";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Carousel";

					
			public static readonly ID ItemsFieldId = new ID("24071b88-2093-4f1e-9b6a-f3aa274a64ac");
			public const string ItemsFieldName = "Items";
			
					
			public static readonly ID TitleFieldId = new ID("edaf25d3-c80a-45b2-8d90-7ca4db15080e");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// Carousel
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Carousel/Carousel Content/Carousel</para>	
	/// <para>ID: 49393afb-4a02-4f34-acf1-fec86916bb47</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarouselConstants.TemplateIdString, AutoMap = true)] //, Cachable = true
	public partial class Carousel  : GlassBase, ICarousel 
	{
	   
						/// <summary>
				/// The Items field.
				/// <para></para>
				/// <para>Field Type: Multilist</para>		
				/// <para>Field ID: 24071b88-2093-4f1e-9b6a-f3aa274a64ac</para>
				/// <para>Custom Data: generic=Books.Foundation.Orm.Models.sitecore.templates.Feature.Carousel.Carousel_Content.ICarouselItem</para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarouselConstants.ItemsFieldName)]
				public virtual IEnumerable<Books.Foundation.Orm.Models.sitecore.templates.Feature.Carousel.Carousel_Content.ICarouselItem> Items  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: edaf25d3-c80a-45b2-8d90-7ca4db15080e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarouselConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}
namespace Books.Foundation.Orm.Models.sitecore.templates.Feature.Banner
{


 	/// <summary>
	/// IBanner Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Banner/Banner</para>	
	/// <para>ID: 5639421c-d88b-43bb-9f80-fc69a8e66f4a</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBannerConstants.TemplateIdString, AutoMap = true )] //, Cachable = true
	public partial interface IBanner : IGlassBase 
	{
								/// <summary>
					/// The Content field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: cfe9bb32-5380-47c7-9b59-8f63c8e9148e</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBannerConstants.ContentFieldName)]
					string Content  {get; set;}
			
								/// <summary>
					/// The CTA field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 4d96c033-0158-4b1b-87ef-cd5ce563fd6c</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBannerConstants.CTAFieldName)]
					Link CTA  {get; set;}
			
								/// <summary>
					/// The Img field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: ae012d8d-e0c9-4b93-a141-61b0e6ee3acf</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBannerConstants.ImgFieldName)]
					Image Img  {get; set;}
			
								/// <summary>
					/// The Sub field.
					/// <para></para>
					/// <para>Field Type: Message Text Line</para>		
					/// <para>Field ID: 7c4c7eeb-fe18-4bdb-b532-f0eb1f84f606</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBannerConstants.SubFieldName)]
					object /* UNKNOWN */ Sub  {get; set;}
			
								/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 279a8736-2ebf-4903-8fa4-5d63826a89b3</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBannerConstants.TitleFieldName)]
					string Title  {get; set;}
			
				}


	public static partial class IBannerConstants{

			public const string TemplateIdString = "5639421c-d88b-43bb-9f80-fc69a8e66f4a";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Banner";

					
			public static readonly ID ContentFieldId = new ID("cfe9bb32-5380-47c7-9b59-8f63c8e9148e");
			public const string ContentFieldName = "Content";
			
					
			public static readonly ID CTAFieldId = new ID("4d96c033-0158-4b1b-87ef-cd5ce563fd6c");
			public const string CTAFieldName = "CTA";
			
					
			public static readonly ID ImgFieldId = new ID("ae012d8d-e0c9-4b93-a141-61b0e6ee3acf");
			public const string ImgFieldName = "Img";
			
					
			public static readonly ID SubFieldId = new ID("7c4c7eeb-fe18-4bdb-b532-f0eb1f84f606");
			public const string SubFieldName = "Sub";
			
					
			public static readonly ID TitleFieldId = new ID("279a8736-2ebf-4903-8fa4-5d63826a89b3");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// Banner
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Banner/Banner</para>	
	/// <para>ID: 5639421c-d88b-43bb-9f80-fc69a8e66f4a</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBannerConstants.TemplateIdString, AutoMap = true)] //, Cachable = true
	public partial class Banner  : GlassBase, IBanner 
	{
	   
						/// <summary>
				/// The Content field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: cfe9bb32-5380-47c7-9b59-8f63c8e9148e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBannerConstants.ContentFieldName)]
				public virtual string Content  {get; set;}
					
						/// <summary>
				/// The CTA field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 4d96c033-0158-4b1b-87ef-cd5ce563fd6c</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBannerConstants.CTAFieldName)]
				public virtual Link CTA  {get; set;}
					
						/// <summary>
				/// The Img field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: ae012d8d-e0c9-4b93-a141-61b0e6ee3acf</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBannerConstants.ImgFieldName)]
				public virtual Image Img  {get; set;}
					
						/// <summary>
				/// The Sub field.
				/// <para></para>
				/// <para>Field Type: Message Text Line</para>		
				/// <para>Field ID: 7c4c7eeb-fe18-4bdb-b532-f0eb1f84f606</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBannerConstants.SubFieldName)]
				public virtual object /* UNKNOWN */ Sub  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 279a8736-2ebf-4903-8fa4-5d63826a89b3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBannerConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}
namespace Books.Foundation.Orm.Models.sitecore.templates.Feature.Banner
{


 	/// <summary>
	/// IBanner_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Banner/Banner Folder</para>	
	/// <para>ID: 57c301eb-640e-4b71-ad51-e805b912af5d</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBanner_FolderConstants.TemplateIdString, AutoMap = true )] //, Cachable = true
	public partial interface IBanner_Folder : IGlassBase 
	{
				}


	public static partial class IBanner_FolderConstants{

			public const string TemplateIdString = "57c301eb-640e-4b71-ad51-e805b912af5d";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Banner Folder";

			

	}

	
	/// <summary>
	/// Banner_Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Banner/Banner Folder</para>	
	/// <para>ID: 57c301eb-640e-4b71-ad51-e805b912af5d</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBanner_FolderConstants.TemplateIdString, AutoMap = true)] //, Cachable = true
	public partial class Banner_Folder  : GlassBase, IBanner_Folder 
	{
	   
			
	}
}
namespace Books.Foundation.Orm.Models.sitecore.templates.User_Defined.Base
{


 	/// <summary>
	/// IBook_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Base/Book Folder</para>	
	/// <para>ID: 8d1770ff-6ac6-4aff-bad2-b24c92c31635</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBook_FolderConstants.TemplateIdString, AutoMap = true )] //, Cachable = true
	public partial interface IBook_Folder : IGlassBase 
	{
								/// <summary>
					/// The Books field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 7e598646-b904-4d02-9c61-a230ff08067d</para>
					/// <para>Custom Data: generic=Books.Foundation.Orm.Models.sitecore.templates.User_Defined.Base.IBase_Book</para>
					/// </summary>
					[SitecoreField(IBook_FolderConstants.BooksFieldName)]
					IEnumerable<Books.Foundation.Orm.Models.sitecore.templates.User_Defined.Base.IBase_Book> Books  {get; set;}
			
				}


	public static partial class IBook_FolderConstants{

			public const string TemplateIdString = "8d1770ff-6ac6-4aff-bad2-b24c92c31635";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Book Folder";

					
			public static readonly ID BooksFieldId = new ID("7e598646-b904-4d02-9c61-a230ff08067d");
			public const string BooksFieldName = "Books";
			
			

	}

	
	/// <summary>
	/// Book_Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Base/Book Folder</para>	
	/// <para>ID: 8d1770ff-6ac6-4aff-bad2-b24c92c31635</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBook_FolderConstants.TemplateIdString, AutoMap = true)] //, Cachable = true
	public partial class Book_Folder  : GlassBase, IBook_Folder 
	{
	   
						/// <summary>
				/// The Books field.
				/// <para></para>
				/// <para>Field Type: Multilist</para>		
				/// <para>Field ID: 7e598646-b904-4d02-9c61-a230ff08067d</para>
				/// <para>Custom Data: generic=Books.Foundation.Orm.Models.sitecore.templates.User_Defined.Base.IBase_Book</para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBook_FolderConstants.BooksFieldName)]
				public virtual IEnumerable<Books.Foundation.Orm.Models.sitecore.templates.User_Defined.Base.IBase_Book> Books  {get; set;}
					
			
	}
}
namespace Books.Foundation.Orm.Models.sitecore.templates.User_Defined.Base
{


 	/// <summary>
	/// IBase_Book Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Base/Base Book</para>	
	/// <para>ID: 99712e59-a583-46fa-afcd-cc2a5223bc41</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBase_BookConstants.TemplateIdString, AutoMap = true )] //, Cachable = true
	public partial interface IBase_Book : IGlassBase , global::Books.Foundation.Orm.Models.sitecore.templates.User_Defined.Base.IBase_Navigation
	{
								/// <summary>
					/// The Author field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 671e4567-9664-4394-b62e-a109b0719dda</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBase_BookConstants.AuthorFieldName)]
					string Author  {get; set;}
			
								/// <summary>
					/// The BookReview field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: f31d59bd-8101-4121-bd64-6cb140b15276</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBase_BookConstants.BookReviewFieldName)]
					string BookReview  {get; set;}
			
								/// <summary>
					/// The Genre field.
					/// <para></para>
					/// <para>Field Type: Droplink</para>		
					/// <para>Field ID: 5399d9b2-b652-4561-a2fe-73002e3b93be</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBase_BookConstants.GenreFieldName)]
					Guid Genre  {get; set;}
			
								/// <summary>
					/// The Img field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 22a8e1f4-55b3-4a9e-8b9d-0fb46db6ff5f</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBase_BookConstants.ImgFieldName)]
					Image Img  {get; set;}
			
								/// <summary>
					/// The Intro field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: 3a7ff6b1-0a29-4c0e-aa05-b7d3f04671c5</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBase_BookConstants.IntroFieldName)]
					string Intro  {get; set;}
			
								/// <summary>
					/// The Link field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 8c449327-2659-43e0-baea-01d4dfe4b9ae</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBase_BookConstants.LinkFieldName)]
					Link Link  {get; set;}
			
								/// <summary>
					/// The PublishDate field.
					/// <para></para>
					/// <para>Field Type: Date</para>		
					/// <para>Field ID: 7415e376-8e56-44dc-b027-69d51d5e01dc</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBase_BookConstants.PublishDateFieldName)]
					DateTime PublishDate  {get; set;}
			
								/// <summary>
					/// The Rating field.
					/// <para></para>
					/// <para>Field Type: Integer</para>		
					/// <para>Field ID: ddd976bb-8631-465c-bcf3-484bd8971b92</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBase_BookConstants.RatingFieldName)]
					int Rating  {get; set;}
			
								/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 1649878b-0c2d-45a1-a84d-c125c641c98c</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBase_BookConstants.TitleFieldName)]
					string Title  {get; set;}
			
				}


	public static partial class IBase_BookConstants{

			public const string TemplateIdString = "99712e59-a583-46fa-afcd-cc2a5223bc41";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Base Book";

					
			public static readonly ID AuthorFieldId = new ID("671e4567-9664-4394-b62e-a109b0719dda");
			public const string AuthorFieldName = "Author";
			
					
			public static readonly ID BookReviewFieldId = new ID("f31d59bd-8101-4121-bd64-6cb140b15276");
			public const string BookReviewFieldName = "BookReview";
			
					
			public static readonly ID GenreFieldId = new ID("5399d9b2-b652-4561-a2fe-73002e3b93be");
			public const string GenreFieldName = "Genre";
			
					
			public static readonly ID ImgFieldId = new ID("22a8e1f4-55b3-4a9e-8b9d-0fb46db6ff5f");
			public const string ImgFieldName = "Img";
			
					
			public static readonly ID IntroFieldId = new ID("3a7ff6b1-0a29-4c0e-aa05-b7d3f04671c5");
			public const string IntroFieldName = "Intro";
			
					
			public static readonly ID LinkFieldId = new ID("8c449327-2659-43e0-baea-01d4dfe4b9ae");
			public const string LinkFieldName = "Link";
			
					
			public static readonly ID PublishDateFieldId = new ID("7415e376-8e56-44dc-b027-69d51d5e01dc");
			public const string PublishDateFieldName = "PublishDate";
			
					
			public static readonly ID RatingFieldId = new ID("ddd976bb-8631-465c-bcf3-484bd8971b92");
			public const string RatingFieldName = "Rating";
			
					
			public static readonly ID TitleFieldId = new ID("1649878b-0c2d-45a1-a84d-c125c641c98c");
			public const string TitleFieldName = "Title";
			
					
			public static readonly ID ExcludeFromNavigationFieldId = new ID("c7e1e333-3593-40ae-8a54-4317665e813c");
			public const string ExcludeFromNavigationFieldName = "ExcludeFromNavigation";
			
					
			public static readonly ID LogoFieldId = new ID("700f5aa2-1ab1-435b-9ced-cc4b71cd5c0d");
			public const string LogoFieldName = "Logo";
			
			

	}

	
	/// <summary>
	/// Base_Book
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Base/Base Book</para>	
	/// <para>ID: 99712e59-a583-46fa-afcd-cc2a5223bc41</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBase_BookConstants.TemplateIdString, AutoMap = true)] //, Cachable = true
	public partial class Base_Book  : GlassBase, IBase_Book 
	{
	   
						/// <summary>
				/// The Author field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 671e4567-9664-4394-b62e-a109b0719dda</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBase_BookConstants.AuthorFieldName)]
				public virtual string Author  {get; set;}
					
						/// <summary>
				/// The BookReview field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: f31d59bd-8101-4121-bd64-6cb140b15276</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBase_BookConstants.BookReviewFieldName)]
				public virtual string BookReview  {get; set;}
					
						/// <summary>
				/// The Genre field.
				/// <para></para>
				/// <para>Field Type: Droplink</para>		
				/// <para>Field ID: 5399d9b2-b652-4561-a2fe-73002e3b93be</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBase_BookConstants.GenreFieldName)]
				public virtual Guid Genre  {get; set;}
					
						/// <summary>
				/// The Img field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 22a8e1f4-55b3-4a9e-8b9d-0fb46db6ff5f</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBase_BookConstants.ImgFieldName)]
				public virtual Image Img  {get; set;}
					
						/// <summary>
				/// The Intro field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 3a7ff6b1-0a29-4c0e-aa05-b7d3f04671c5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBase_BookConstants.IntroFieldName)]
				public virtual string Intro  {get; set;}
					
						/// <summary>
				/// The Link field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 8c449327-2659-43e0-baea-01d4dfe4b9ae</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBase_BookConstants.LinkFieldName)]
				public virtual Link Link  {get; set;}
					
						/// <summary>
				/// The PublishDate field.
				/// <para></para>
				/// <para>Field Type: Date</para>		
				/// <para>Field ID: 7415e376-8e56-44dc-b027-69d51d5e01dc</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBase_BookConstants.PublishDateFieldName)]
				public virtual DateTime PublishDate  {get; set;}
					
						/// <summary>
				/// The Rating field.
				/// <para></para>
				/// <para>Field Type: Integer</para>		
				/// <para>Field ID: ddd976bb-8631-465c-bcf3-484bd8971b92</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBase_BookConstants.RatingFieldName)]
				public virtual int Rating  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 1649878b-0c2d-45a1-a84d-c125c641c98c</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBase_BookConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The ExcludeFromNavigation field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: c7e1e333-3593-40ae-8a54-4317665e813c</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBase_BookConstants.ExcludeFromNavigationFieldName)]
				public virtual bool ExcludeFromNavigation  {get; set;}
					
						/// <summary>
				/// The Logo field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 700f5aa2-1ab1-435b-9ced-cc4b71cd5c0d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBase_BookConstants.LogoFieldName)]
				public virtual Image Logo  {get; set;}
					
			
	}
}
namespace Books.Foundation.Orm.Models.sitecore.templates.Feature.Navigation
{


 	/// <summary>
	/// INavigationItem Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Navigation/NavigationItem</para>	
	/// <para>ID: b2eec395-f134-463d-bcac-baf3735ca4f7</para>	
	/// </summary>
	[SitecoreType(TemplateId=INavigationItemConstants.TemplateIdString, AutoMap = true )] //, Cachable = true
	public partial interface INavigationItem : IGlassBase 
	{
								/// <summary>
					/// The Active field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: a04bd9aa-683d-44f4-b900-5a99c6f5dfed</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(INavigationItemConstants.ActiveFieldName)]
					bool Active  {get; set;}
			
								/// <summary>
					/// The ChildLinks field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 324e751f-491a-4da6-a211-0e63bd157f18</para>
					/// <para>Custom Data: generic=Books.Foundation.Orm.Models.sitecore.templates.Feature.Navigation.INavigationItem</para>
					/// </summary>
					[SitecoreField(INavigationItemConstants.ChildLinksFieldName)]
					IEnumerable<Books.Foundation.Orm.Models.sitecore.templates.Feature.Navigation.INavigationItem> ChildLinks  {get; set;}
			
								/// <summary>
					/// The Link field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 2ed8e0bb-2dcc-4b29-8fa4-a16b06c48be2</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(INavigationItemConstants.LinkFieldName)]
					Link Link  {get; set;}
			
								/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: d5d53323-62fb-4530-8de6-a4a82f4ebb30</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(INavigationItemConstants.TitleFieldName)]
					string Title  {get; set;}
			
				}


	public static partial class INavigationItemConstants{

			public const string TemplateIdString = "b2eec395-f134-463d-bcac-baf3735ca4f7";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "NavigationItem";

					
			public static readonly ID ActiveFieldId = new ID("a04bd9aa-683d-44f4-b900-5a99c6f5dfed");
			public const string ActiveFieldName = "Active";
			
					
			public static readonly ID ChildLinksFieldId = new ID("324e751f-491a-4da6-a211-0e63bd157f18");
			public const string ChildLinksFieldName = "ChildLinks";
			
					
			public static readonly ID LinkFieldId = new ID("2ed8e0bb-2dcc-4b29-8fa4-a16b06c48be2");
			public const string LinkFieldName = "Link";
			
					
			public static readonly ID TitleFieldId = new ID("d5d53323-62fb-4530-8de6-a4a82f4ebb30");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// NavigationItem
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Navigation/NavigationItem</para>	
	/// <para>ID: b2eec395-f134-463d-bcac-baf3735ca4f7</para>	
	/// </summary>
	[SitecoreType(TemplateId=INavigationItemConstants.TemplateIdString, AutoMap = true)] //, Cachable = true
	public partial class NavigationItem  : GlassBase, INavigationItem 
	{
	   
						/// <summary>
				/// The Active field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: a04bd9aa-683d-44f4-b900-5a99c6f5dfed</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(INavigationItemConstants.ActiveFieldName)]
				public virtual bool Active  {get; set;}
					
						/// <summary>
				/// The ChildLinks field.
				/// <para></para>
				/// <para>Field Type: Multilist</para>		
				/// <para>Field ID: 324e751f-491a-4da6-a211-0e63bd157f18</para>
				/// <para>Custom Data: generic=Books.Foundation.Orm.Models.sitecore.templates.Feature.Navigation.INavigationItem</para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(INavigationItemConstants.ChildLinksFieldName)]
				public virtual IEnumerable<Books.Foundation.Orm.Models.sitecore.templates.Feature.Navigation.INavigationItem> ChildLinks  {get; set;}
					
						/// <summary>
				/// The Link field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 2ed8e0bb-2dcc-4b29-8fa4-a16b06c48be2</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(INavigationItemConstants.LinkFieldName)]
				public virtual Link Link  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: d5d53323-62fb-4530-8de6-a4a82f4ebb30</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(INavigationItemConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}
namespace Books.Foundation.Orm.Models.sitecore.templates.User_Defined.Base
{


 	/// <summary>
	/// IBase_Navigation Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Base/Base Navigation</para>	
	/// <para>ID: b651325b-cf69-4b30-916d-7a8e51ea3fc5</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBase_NavigationConstants.TemplateIdString, AutoMap = true )] //, Cachable = true
	public partial interface IBase_Navigation : IGlassBase 
	{
								/// <summary>
					/// The ExcludeFromNavigation field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: c7e1e333-3593-40ae-8a54-4317665e813c</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBase_NavigationConstants.ExcludeFromNavigationFieldName)]
					bool ExcludeFromNavigation  {get; set;}
			
								/// <summary>
					/// The Logo field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 700f5aa2-1ab1-435b-9ced-cc4b71cd5c0d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBase_NavigationConstants.LogoFieldName)]
					Image Logo  {get; set;}
			
				}


	public static partial class IBase_NavigationConstants{

			public const string TemplateIdString = "b651325b-cf69-4b30-916d-7a8e51ea3fc5";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Base Navigation";

					
			public static readonly ID ExcludeFromNavigationFieldId = new ID("c7e1e333-3593-40ae-8a54-4317665e813c");
			public const string ExcludeFromNavigationFieldName = "ExcludeFromNavigation";
			
					
			public static readonly ID LogoFieldId = new ID("700f5aa2-1ab1-435b-9ced-cc4b71cd5c0d");
			public const string LogoFieldName = "Logo";
			
			

	}

	
	/// <summary>
	/// Base_Navigation
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Base/Base Navigation</para>	
	/// <para>ID: b651325b-cf69-4b30-916d-7a8e51ea3fc5</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBase_NavigationConstants.TemplateIdString, AutoMap = true)] //, Cachable = true
	public partial class Base_Navigation  : GlassBase, IBase_Navigation 
	{
	   
						/// <summary>
				/// The ExcludeFromNavigation field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: c7e1e333-3593-40ae-8a54-4317665e813c</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBase_NavigationConstants.ExcludeFromNavigationFieldName)]
				public virtual bool ExcludeFromNavigation  {get; set;}
					
						/// <summary>
				/// The Logo field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 700f5aa2-1ab1-435b-9ced-cc4b71cd5c0d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBase_NavigationConstants.LogoFieldName)]
				public virtual Image Logo  {get; set;}
					
			
	}
}
namespace Books.Foundation.Orm.Models.sitecore.templates.User_Defined
{


 	/// <summary>
	/// IData Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Data</para>	
	/// <para>ID: c2bd0ead-3823-4a5e-ad3d-dd95758def1d</para>	
	/// </summary>
	[SitecoreType(TemplateId=IDataConstants.TemplateIdString, AutoMap = true )] //, Cachable = true
	public partial interface IData : IGlassBase 
	{
				}


	public static partial class IDataConstants{

			public const string TemplateIdString = "c2bd0ead-3823-4a5e-ad3d-dd95758def1d";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Data";

			

	}

	
	/// <summary>
	/// Data
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Data</para>	
	/// <para>ID: c2bd0ead-3823-4a5e-ad3d-dd95758def1d</para>	
	/// </summary>
	[SitecoreType(TemplateId=IDataConstants.TemplateIdString, AutoMap = true)] //, Cachable = true
	public partial class Data  : GlassBase, IData 
	{
	   
			
	}
}
namespace Books.Foundation.Orm.Models.sitecore.templates.User_Defined.Base
{


 	/// <summary>
	/// I_Base_Heading_Decoration Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Base/_Base Heading Decoration</para>	
	/// <para>ID: ca3aea07-1534-4e4a-91fa-ed2ec2923a6c</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_Heading_DecorationConstants.TemplateIdString, AutoMap = true )] //, Cachable = true
	public partial interface I_Base_Heading_Decoration : IGlassBase 
	{
								/// <summary>
					/// The DecorationBanner field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 34f8fde4-8e5e-46dd-8a3f-2e93b475742e</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Base_Heading_DecorationConstants.DecorationBannerFieldName)]
					Image DecorationBanner  {get; set;}
			
				}


	public static partial class I_Base_Heading_DecorationConstants{

			public const string TemplateIdString = "ca3aea07-1534-4e4a-91fa-ed2ec2923a6c";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Base Heading Decoration";

					
			public static readonly ID DecorationBannerFieldId = new ID("34f8fde4-8e5e-46dd-8a3f-2e93b475742e");
			public const string DecorationBannerFieldName = "DecorationBanner";
			
			

	}

	
	/// <summary>
	/// _Base_Heading_Decoration
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Base/_Base Heading Decoration</para>	
	/// <para>ID: ca3aea07-1534-4e4a-91fa-ed2ec2923a6c</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_Heading_DecorationConstants.TemplateIdString, AutoMap = true)] //, Cachable = true
	public partial class _Base_Heading_Decoration  : GlassBase, I_Base_Heading_Decoration 
	{
	   
						/// <summary>
				/// The DecorationBanner field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 34f8fde4-8e5e-46dd-8a3f-2e93b475742e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Base_Heading_DecorationConstants.DecorationBannerFieldName)]
				public virtual Image DecorationBanner  {get; set;}
					
			
	}
}
namespace Books.Foundation.Orm.Models.sitecore.templates.Feature.Navigation
{


 	/// <summary>
	/// INavigation_Links_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Navigation/Navigation Links Folder</para>	
	/// <para>ID: d3c0f83d-45c5-4b15-a70c-a2032d119a1d</para>	
	/// </summary>
	[SitecoreType(TemplateId=INavigation_Links_FolderConstants.TemplateIdString, AutoMap = true )] //, Cachable = true
	public partial interface INavigation_Links_Folder : IGlassBase , global::Books.Foundation.Orm.Models.sitecore.templates.User_Defined.Base.IBase_Navigation
	{
								/// <summary>
					/// The Items field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: a2658dba-b4d9-4836-8f2f-7efd7c9eaaa6</para>
					/// <para>Custom Data: generic=Books.Foundation.Orm.Models.sitecore.templates.Feature.Navigation.INavigationItem</para>
					/// </summary>
					[SitecoreField(INavigation_Links_FolderConstants.ItemsFieldName)]
					IEnumerable<Books.Foundation.Orm.Models.sitecore.templates.Feature.Navigation.INavigationItem> Items  {get; set;}
			
				}


	public static partial class INavigation_Links_FolderConstants{

			public const string TemplateIdString = "d3c0f83d-45c5-4b15-a70c-a2032d119a1d";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Navigation Links Folder";

					
			public static readonly ID ItemsFieldId = new ID("a2658dba-b4d9-4836-8f2f-7efd7c9eaaa6");
			public const string ItemsFieldName = "Items";
			
					
			public static readonly ID ExcludeFromNavigationFieldId = new ID("c7e1e333-3593-40ae-8a54-4317665e813c");
			public const string ExcludeFromNavigationFieldName = "ExcludeFromNavigation";
			
					
			public static readonly ID LogoFieldId = new ID("700f5aa2-1ab1-435b-9ced-cc4b71cd5c0d");
			public const string LogoFieldName = "Logo";
			
			

	}

	
	/// <summary>
	/// Navigation_Links_Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Navigation/Navigation Links Folder</para>	
	/// <para>ID: d3c0f83d-45c5-4b15-a70c-a2032d119a1d</para>	
	/// </summary>
	[SitecoreType(TemplateId=INavigation_Links_FolderConstants.TemplateIdString, AutoMap = true)] //, Cachable = true
	public partial class Navigation_Links_Folder  : GlassBase, INavigation_Links_Folder 
	{
	   
						/// <summary>
				/// The Items field.
				/// <para></para>
				/// <para>Field Type: Multilist</para>		
				/// <para>Field ID: a2658dba-b4d9-4836-8f2f-7efd7c9eaaa6</para>
				/// <para>Custom Data: generic=Books.Foundation.Orm.Models.sitecore.templates.Feature.Navigation.INavigationItem</para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(INavigation_Links_FolderConstants.ItemsFieldName)]
				public virtual IEnumerable<Books.Foundation.Orm.Models.sitecore.templates.Feature.Navigation.INavigationItem> Items  {get; set;}
					
						/// <summary>
				/// The ExcludeFromNavigation field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: c7e1e333-3593-40ae-8a54-4317665e813c</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(INavigation_Links_FolderConstants.ExcludeFromNavigationFieldName)]
				public virtual bool ExcludeFromNavigation  {get; set;}
					
						/// <summary>
				/// The Logo field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 700f5aa2-1ab1-435b-9ced-cc4b71cd5c0d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(INavigation_Links_FolderConstants.LogoFieldName)]
				public virtual Image Logo  {get; set;}
					
			
	}
}
namespace Books.Foundation.Orm.Models.sitecore.templates.Feature.Carousel
{


 	/// <summary>
	/// ICarousel_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Carousel/Carousel Folder</para>	
	/// <para>ID: d3ed7aa7-33ac-46f4-a730-e5eb84cc017b</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarousel_FolderConstants.TemplateIdString, AutoMap = true )] //, Cachable = true
	public partial interface ICarousel_Folder : IGlassBase 
	{
				}


	public static partial class ICarousel_FolderConstants{

			public const string TemplateIdString = "d3ed7aa7-33ac-46f4-a730-e5eb84cc017b";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Carousel Folder";

			

	}

	
	/// <summary>
	/// Carousel_Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Carousel/Carousel Folder</para>	
	/// <para>ID: d3ed7aa7-33ac-46f4-a730-e5eb84cc017b</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarousel_FolderConstants.TemplateIdString, AutoMap = true)] //, Cachable = true
	public partial class Carousel_Folder  : GlassBase, ICarousel_Folder 
	{
	   
			
	}
}
namespace Books.Foundation.Orm.Models.sitecore.templates.Project.Page_Types
{


 	/// <summary>
	/// IHome Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Page Types/Home</para>	
	/// <para>ID: e006e803-dd5c-46ab-aa6b-419a52b657be</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeConstants.TemplateIdString, AutoMap = true )] //, Cachable = true
	public partial interface IHome : IGlassBase , global::Books.Foundation.Orm.Models.sitecore.templates.User_Defined.Base.I_Base_Content, global::Books.Foundation.Orm.Models.sitecore.templates.User_Defined.Base.I_Base_Heading_Decoration
	{
				}


	public static partial class IHomeConstants{

			public const string TemplateIdString = "e006e803-dd5c-46ab-aa6b-419a52b657be";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Home";

					
			public static readonly ID ContentBodyFieldId = new ID("8af829a4-3a05-4df4-8028-9505c7fd3d65");
			public const string ContentBodyFieldName = "ContentBody";
			
					
			public static readonly ID DecorationBannerFieldId = new ID("34f8fde4-8e5e-46dd-8a3f-2e93b475742e");
			public const string DecorationBannerFieldName = "DecorationBanner";
			
			

	}

	
	/// <summary>
	/// Home
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Page Types/Home</para>	
	/// <para>ID: e006e803-dd5c-46ab-aa6b-419a52b657be</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeConstants.TemplateIdString, AutoMap = true)] //, Cachable = true
	public partial class Home  : GlassBase, IHome 
	{
	   
						/// <summary>
				/// The ContentBody field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 8af829a4-3a05-4df4-8028-9505c7fd3d65</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.ContentBodyFieldName)]
				public virtual string ContentBody  {get; set;}
					
						/// <summary>
				/// The DecorationBanner field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 34f8fde4-8e5e-46dd-8a3f-2e93b475742e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.DecorationBannerFieldName)]
				public virtual Image DecorationBanner  {get; set;}
					
			
	}
}
namespace Books.Foundation.Orm.Models.sitecore.templates.User_Defined.Base
{


 	/// <summary>
	/// IBase_Footer Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Base/Base Footer</para>	
	/// <para>ID: e1860135-0069-461d-a435-08602253fb5c</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBase_FooterConstants.TemplateIdString, AutoMap = true )] //, Cachable = true
	public partial interface IBase_Footer : IGlassBase 
	{
								/// <summary>
					/// The Content field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: ff5ce688-42c6-47fe-97fc-ace47571a222</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBase_FooterConstants.ContentFieldName)]
					string Content  {get; set;}
			
								/// <summary>
					/// The Copyright field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 477c7db6-ceb4-4da4-84d4-c482d897ac2c</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBase_FooterConstants.CopyrightFieldName)]
					string Copyright  {get; set;}
			
								/// <summary>
					/// The Header field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 672c7e6a-6e84-4936-a07e-0ff82aa2f957</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBase_FooterConstants.HeaderFieldName)]
					string Header  {get; set;}
			
								/// <summary>
					/// The Subhead field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: cb8bd673-36f1-4793-8310-3f02fdca1a86</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBase_FooterConstants.SubheadFieldName)]
					string Subhead  {get; set;}
			
				}


	public static partial class IBase_FooterConstants{

			public const string TemplateIdString = "e1860135-0069-461d-a435-08602253fb5c";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Base Footer";

					
			public static readonly ID ContentFieldId = new ID("ff5ce688-42c6-47fe-97fc-ace47571a222");
			public const string ContentFieldName = "Content";
			
					
			public static readonly ID CopyrightFieldId = new ID("477c7db6-ceb4-4da4-84d4-c482d897ac2c");
			public const string CopyrightFieldName = "Copyright";
			
					
			public static readonly ID HeaderFieldId = new ID("672c7e6a-6e84-4936-a07e-0ff82aa2f957");
			public const string HeaderFieldName = "Header";
			
					
			public static readonly ID SubheadFieldId = new ID("cb8bd673-36f1-4793-8310-3f02fdca1a86");
			public const string SubheadFieldName = "Subhead";
			
			

	}

	
	/// <summary>
	/// Base_Footer
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Base/Base Footer</para>	
	/// <para>ID: e1860135-0069-461d-a435-08602253fb5c</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBase_FooterConstants.TemplateIdString, AutoMap = true)] //, Cachable = true
	public partial class Base_Footer  : GlassBase, IBase_Footer 
	{
	   
						/// <summary>
				/// The Content field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: ff5ce688-42c6-47fe-97fc-ace47571a222</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBase_FooterConstants.ContentFieldName)]
				public virtual string Content  {get; set;}
					
						/// <summary>
				/// The Copyright field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 477c7db6-ceb4-4da4-84d4-c482d897ac2c</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBase_FooterConstants.CopyrightFieldName)]
				public virtual string Copyright  {get; set;}
					
						/// <summary>
				/// The Header field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 672c7e6a-6e84-4936-a07e-0ff82aa2f957</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBase_FooterConstants.HeaderFieldName)]
				public virtual string Header  {get; set;}
					
						/// <summary>
				/// The Subhead field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: cb8bd673-36f1-4793-8310-3f02fdca1a86</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBase_FooterConstants.SubheadFieldName)]
				public virtual string Subhead  {get; set;}
					
			
	}
}
namespace Books.Foundation.Orm.Models.sitecore.templates.Project.Page_Types
{


 	/// <summary>
	/// IError Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Page Types/Error</para>	
	/// <para>ID: e6fbf178-9a2e-4c9f-8d77-3c5c428e43b2</para>	
	/// </summary>
	[SitecoreType(TemplateId=IErrorConstants.TemplateIdString, AutoMap = true )] //, Cachable = true
	public partial interface IError : IGlassBase , global::Books.Foundation.Orm.Models.sitecore.templates.User_Defined.Base.IBasePage
	{
								/// <summary>
					/// The Description__Error field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: d7f75437-3b1d-4ed6-88ca-d2afc7b02478</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IErrorConstants.Description__ErrorFieldName)]
					string Description__Error  {get; set;}
			
								/// <summary>
					/// The Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 207a38ee-390d-4e76-9fd0-06225f9bc984</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IErrorConstants.ImageFieldName)]
					Image Image  {get; set;}
			
								/// <summary>
					/// The Link field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 6fce48b7-50ab-4427-96d5-fc074f252a1c</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IErrorConstants.LinkFieldName)]
					Link Link  {get; set;}
			
								/// <summary>
					/// The Type_Error field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 8d62cded-21d8-437e-baa2-ad39fed1f623</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IErrorConstants.Type_ErrorFieldName)]
					string Type_Error  {get; set;}
			
				}


	public static partial class IErrorConstants{

			public const string TemplateIdString = "e6fbf178-9a2e-4c9f-8d77-3c5c428e43b2";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Error";

					
			public static readonly ID Description__ErrorFieldId = new ID("d7f75437-3b1d-4ed6-88ca-d2afc7b02478");
			public const string Description__ErrorFieldName = "Description__Error";
			
					
			public static readonly ID ImageFieldId = new ID("207a38ee-390d-4e76-9fd0-06225f9bc984");
			public const string ImageFieldName = "Image";
			
					
			public static readonly ID LinkFieldId = new ID("6fce48b7-50ab-4427-96d5-fc074f252a1c");
			public const string LinkFieldName = "Link";
			
					
			public static readonly ID Type_ErrorFieldId = new ID("8d62cded-21d8-437e-baa2-ad39fed1f623");
			public const string Type_ErrorFieldName = "Type_Error";
			
					
			public static readonly ID Sub_TitleFieldId = new ID("43260204-717e-421e-aeb0-5b8e572a4d26");
			public const string Sub_TitleFieldName = "Sub Title";
			
					
			public static readonly ID TitleFieldId = new ID("e8674014-f36c-407f-8217-9c16bd3d9adf");
			public const string TitleFieldName = "Title";
			
					
			public static readonly ID MetaDescriptionFieldId = new ID("ed4089e1-c500-4c02-beaf-bd624ca82270");
			public const string MetaDescriptionFieldName = "MetaDescription";
			
					
			public static readonly ID MetaTitleFieldId = new ID("0f80d938-d0aa-4191-9f44-7f1c32a39ce4");
			public const string MetaTitleFieldName = "MetaTitle";
			
			

	}

	
	/// <summary>
	/// Error
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/Page Types/Error</para>	
	/// <para>ID: e6fbf178-9a2e-4c9f-8d77-3c5c428e43b2</para>	
	/// </summary>
	[SitecoreType(TemplateId=IErrorConstants.TemplateIdString, AutoMap = true)] //, Cachable = true
	public partial class Error  : GlassBase, IError 
	{
	   
						/// <summary>
				/// The Description__Error field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: d7f75437-3b1d-4ed6-88ca-d2afc7b02478</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IErrorConstants.Description__ErrorFieldName)]
				public virtual string Description__Error  {get; set;}
					
						/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 207a38ee-390d-4e76-9fd0-06225f9bc984</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IErrorConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
						/// <summary>
				/// The Link field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 6fce48b7-50ab-4427-96d5-fc074f252a1c</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IErrorConstants.LinkFieldName)]
				public virtual Link Link  {get; set;}
					
						/// <summary>
				/// The Type_Error field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 8d62cded-21d8-437e-baa2-ad39fed1f623</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IErrorConstants.Type_ErrorFieldName)]
				public virtual string Type_Error  {get; set;}
					
						/// <summary>
				/// The Sub Title field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 43260204-717e-421e-aeb0-5b8e572a4d26</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IErrorConstants.Sub_TitleFieldName)]
				public virtual string Sub_Title  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: e8674014-f36c-407f-8217-9c16bd3d9adf</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IErrorConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ed4089e1-c500-4c02-beaf-bd624ca82270</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IErrorConstants.MetaDescriptionFieldName)]
				public virtual string MetaDescription  {get; set;}
					
						/// <summary>
				/// The MetaTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 0f80d938-d0aa-4191-9f44-7f1c32a39ce4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IErrorConstants.MetaTitleFieldName)]
				public virtual string MetaTitle  {get; set;}
					
			
	}
}
